[package]
name = 'questar'
version = '1.0.0'
upgrade_policy = "compatible"

[addresses]
questar_addr = '0x1f3dfe4bd7c58129960609006c32bc6dd6cd24d5b0fbf091780e29c5360dca48'

[dev-addresses]
questar_addr = '0x1f3dfe4bd7c58129960609006c32bc6dd6cd24d5b0fbf091780e29c5360dca48'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'
